FROM Ubuntu 

RUN apt-get update 
RUN apt-get install python 

RUN pip install flask 
RUN pip install flask-mysql 

COPY . /opt/sourcecode 
ENTRYPOINT FLASK_APP=/opt/sourcecode/app.py flask run 
